/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package juegosokoban;

/**
 *
 * @author Diego Felipe y Brahian Gonzales
 */
//clase que vota la ventana gano
//da las opciones correspondientes si ha ganado si ha ganado
public class Ganar extends javax.swing.JFrame {

    /**
     * Creates new form Ganar
     */
    private Juego juego;
    private NuevoNivel Nivel;
    private String jugador;
    private int nivel;
    private String level;
    
    public Ganar(String jugador1, int level1) {
        initComponents();
        this.jugador=jugador1;
        this.nivel=level1;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLnivel = new javax.swing.JLabel();
        JLsuperado = new javax.swing.JLabel();
        JLtitulo = new javax.swing.JLabel();
        JLopciones = new javax.swing.JLabel();
        JBcontinuar = new javax.swing.JButton();
        JBnewnivel = new javax.swing.JButton();
        JBreiniciar = new javax.swing.JButton();
        JBmenu = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLnivel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        JLnivel.setForeground(new java.awt.Color(204, 204, 0));
        JLnivel.setText("NIVEL");

        JLsuperado.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        JLsuperado.setText("Opciones:");

        JLtitulo.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        JLtitulo.setForeground(new java.awt.Color(51, 153, 0));
        JLtitulo.setText("LION WARRIORS");

        JLopciones.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        JLopciones.setForeground(new java.awt.Color(204, 0, 0));
        JLopciones.setText("SUPERADO");

        JBcontinuar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBcontinuar.setText("Continuar");
        JBcontinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcontinuarActionPerformed(evt);
            }
        });

        JBnewnivel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBnewnivel.setText("Nuevo Nivel");
        JBnewnivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnewnivelActionPerformed(evt);
            }
        });

        JBreiniciar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBreiniciar.setText("Reiniciar");
        JBreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBreiniciarActionPerformed(evt);
            }
        });

        JBmenu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBmenu.setText("Menu");
        JBmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBmenuActionPerformed(evt);
            }
        });

        JBsalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBsalir.setText("Salir");
        JBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLnivel)
                                .addGap(26, 26, 26)
                                .addComponent(JLopciones))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLsuperado)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JBcontinuar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(JBreiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JBnewnivel)
                                    .addComponent(JBmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JLtitulo)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLtitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnivel)
                    .addComponent(JLopciones))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBcontinuar)
                    .addComponent(JLsuperado)
                    .addComponent(JBnewnivel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBreiniciar)
                    .addComponent(JBmenu))
                .addGap(18, 18, 18)
                .addComponent(JBsalir)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //reinicia el nivel en el que se eeste
    private void JBreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBreiniciarActionPerformed
        // TODO add your handling code here:        
        this.level="Nivel "+Integer.toString(this.nivel);
        System.out.println(level);
        this.dispose();
        juego=new Juego(level,jugador);
    }//GEN-LAST:event_JBreiniciarActionPerformed
    //opcion continuar, da paso al siguiente nivel
    private void JBcontinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcontinuarActionPerformed
        // TODO add your handling code here:
        this.nivel=nivel+1;
        this.level="Nivel "+Integer.toString(nivel);
        this.dispose();
        juego=new Juego(level,jugador);
    }//GEN-LAST:event_JBcontinuarActionPerformed
    //opcion nuevo nivel, da a escojer un nuevo nivel
    private void JBnewnivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnewnivelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Nivel=new NuevoNivel(jugador);
        Nivel.setVisible(true);
    }//GEN-LAST:event_JBnewnivelActionPerformed
    //opcion menu, abre la ventana mennu
    private void JBmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBmenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Inicializador n=new Inicializador();
        n.setVisible(true);
    }//GEN-LAST:event_JBmenuActionPerformed
    //opcion salir del juego 
    private void JBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_JBsalirActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBcontinuar;
    private javax.swing.JButton JBmenu;
    private javax.swing.JButton JBnewnivel;
    private javax.swing.JButton JBreiniciar;
    private javax.swing.JButton JBsalir;
    private javax.swing.JLabel JLnivel;
    private javax.swing.JLabel JLopciones;
    private javax.swing.JLabel JLsuperado;
    private javax.swing.JLabel JLtitulo;
    // End of variables declaration//GEN-END:variables
}
