/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package juegosokoban;

/**
 *
 * @author Diego Fleipe y Brahian Gonzales
 */
public class Perder extends javax.swing.JFrame {

    /**
     * Creates new form Perder
     */
    private Juego juego;
    private NuevoNivel Nivel;
    private String jugador;
    private int nivel;
    private String level;
    
    public Perder(String jugador1, int level1) {
        initComponents();
        this.jugador=jugador1;
        this.nivel=level1;  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLnivel = new javax.swing.JLabel();
        JLopciones = new javax.swing.JLabel();
        JLsuperado = new javax.swing.JLabel();
        JBreiniciar = new javax.swing.JButton();
        JBnewnivel = new javax.swing.JButton();
        JBmenu = new javax.swing.JButton();
        JLtitulo = new javax.swing.JLabel();
        JBsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        JLnivel.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        JLnivel.setForeground(new java.awt.Color(204, 204, 0));
        JLnivel.setText("NIVEL");

        JLopciones.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        JLopciones.setForeground(new java.awt.Color(204, 0, 0));
        JLopciones.setText("PERDIDO");

        JLsuperado.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        JLsuperado.setText("Opciones:");

        JBreiniciar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBreiniciar.setText("Reiniciar");
        JBreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBreiniciarActionPerformed(evt);
            }
        });

        JBnewnivel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBnewnivel.setText("Nuevo Nivel");
        JBnewnivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnewnivelActionPerformed(evt);
            }
        });

        JBmenu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBmenu.setText("Menu");
        JBmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBmenuActionPerformed(evt);
            }
        });

        JLtitulo.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        JLtitulo.setForeground(new java.awt.Color(51, 153, 0));
        JLtitulo.setText("LION WARRIORS");

        JBsalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBsalir.setText("Salir");
        JBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLsuperado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBreiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(JBnewnivel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(JLnivel)
                        .addGap(50, 50, 50)
                        .addComponent(JLopciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(JLtitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLtitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnivel)
                    .addComponent(JLopciones))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLsuperado)
                    .addComponent(JBnewnivel)
                    .addComponent(JBreiniciar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBmenu)
                    .addComponent(JBsalir))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBreiniciarActionPerformed
        // TODO add your handling code here:
        this.level="Nivel "+Integer.toString(this.nivel);
        System.out.println(level);
        this.dispose();
        juego=new Juego(level,jugador);
    }//GEN-LAST:event_JBreiniciarActionPerformed

    private void JBnewnivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnewnivelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Nivel=new NuevoNivel(jugador);
        Nivel.setVisible(true);

    }//GEN-LAST:event_JBnewnivelActionPerformed

    private void JBmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBmenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Inicializador n=new Inicializador();
        n.setVisible(true);
    }//GEN-LAST:event_JBmenuActionPerformed

    private void JBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_JBsalirActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBmenu;
    private javax.swing.JButton JBnewnivel;
    private javax.swing.JButton JBreiniciar;
    private javax.swing.JButton JBsalir;
    private javax.swing.JLabel JLnivel;
    private javax.swing.JLabel JLopciones;
    private javax.swing.JLabel JLsuperado;
    private javax.swing.JLabel JLtitulo;
    // End of variables declaration//GEN-END:variables
}
